from django.urls import path, include
from . import views

app_name = 'facturacion'

urlpatterns = [
	path('', views.index, name = 'vIndexFacturacion'),
	path('error/', views.error, name='vError'),
	path('facturas/', include([
		path('page/<int:page>/', views.lista_ventas, name='vVentasPeriodo'),
		path('page/<int:page>/<str:inicio>/<str:final>/', views.lista_ventas, name='vVentasRango'),
		])),
	path('proformas/', include([
		path('page/<int:page>/', views.lista_proformas, name='vListaProformas'),
		#path('<str:todas>/', views.lista_proformas, name='vListaTodasProformas'),
		path('page/<int:page>/<str:inicio>/<str:final>/', views.lista_proformas, name='vListaProformasRango'),
		path('nueva/', views.nueva_proforma, name='vNuevaProforma'),
		path('<int:_id>/ver/', views.ver_proforma, name='vVerProforma'),
		path('<int:_id>/editar/', views.editar_proforma, name='vEditarProforma'),
		path('<int:_id>/reemitir/', views.re_proforma, name='vReemitirProforma'),
		path('<int:_id>/detalle/', views.detalle_proforma, name='vDetalleProforma'),
		path('<int:_id>/anular/', views.anular_proforma, name='vAnularProforma'),
		])),
	path('facturas/', include([
		path('nueva/', views.nueva_factura, name='vNuevaFactura'),
		path('<int:_id>/ver/', views.ver_factura, name='vVerFactura'),
		#path('imprimir/<int:_id>/', views.imprimirFactura, name='vImprimirFactura'),
		#path('liquidar/<int:vendedor>/<str:fecha>', views.liquidarFactura, name='vLiquidarFactura'),
		path('<int:_id>/editar/', views.editar_factura, name='vEditarFactura'),
		#path('<int:_id>/detalle/<int:_idd>/editar/', views.editar_detalle_factura, name='vEditarDetalleFactura'),
		path('<int:_id>/cancelar/', views.cancelar_factura, name='vCancelarFactura'),
		path('<int:_id>/anular/', views.anular_factura, name='vAnularFactura'),
		#path('<int:_id>/entregar/', views.entregarFactura, name='vEntregarFactura'),
		#path('<int:_id>/asiento/', views.asiento_factura, name='vAsientoFactura'),
		#path('<int:_id>/asiento/<int:_ida>/detalle/', views.detalle_asiento_factura, name='vDetalleAsientoFactura'),
		path('<int:_id>/detalle/<int:_idd>/eliminar/', views.eliminar_detalle_factura, name='vEliminarDetalleFactura'),
		path('por-fecha/<str:fecha>/', views.facturas_por_fecha, name='vFacturasPorFecha'),
		path('por-vendedor/<int:_id>/', views.facturas_por_vendedor, name='vFacturasPorVendedor'),
		path('por-fecha-vendedor/<str:fecha>/<int:_id>/', views.facturas_vendedor_fecha, name='vFacturasVendedorFecha'),
		#path('pendientes/', views.listaFacturasPendientes, name='vListaFacturasPendientes'),
		])),
	path('orden-ruta/', include([
		path('page/<int:page>/', views.lista_ordenes_ruta, name='vListaOrdenesRuta'),
		path('nueva/', views.nueva_orden_ruta, name='vNuevaOrdenRuta'),
		path('<int:_id>/ver/', views.ver_orden_ruta, name='vVerOrdenRuta'),
		path('<int:_id>/autorizar/', views.autorizar_orden_ruta, name='vAutorizarOrdenRuta'),
		path('<int:_id>/editar/', views.editar_orden_ruta, name='vEditarOrdenRuta'),
		#path('eliminar/<int:_id>/', views.eliminar_orden_ruta, name='vEliminarOrdenRuta'),
		path('<int:_id>/entregar/', views.entregar_orden_ruta, name='vEntregarOrdenRuta'),
		path('<int:_id>/anular/', views.anular_orden_ruta, name='vAnularOrdenRuta'),
		path('<int:_id>/liquidar/', views.liquidar_orden_ruta, name='vLiquidarOrdenRuta'),
		path('<int:_id>/detalle/', views.detalle_orden_ruta, name='vDetalleOrdenRuta'),
		path('<int:_id>/detalle/<int:_idd>/eliminar/', views.eliminar_detalle_orden_ruta, name='vEliminarDetalleOrdenRuta'),
		#path('detalle/<int:_id>/entregar/', views.entregar_detalle_orden_ruta, name='vEntregarDetalleOrdenRuta'),
		path('por-fecha/<str:fecha>/', views.ordenRutaPorFecha, name='vOrdenRutaPorFecha'),
		path('por-vendedor/<int:_id>/', views.ordenRutaPorVendedor, name='vOrdenRutaPorVendedor'),
		path('por-fecha-vendedor/<str:fecha>/<int:_id>/', views.ordenRutaPorFechaVendedor, name='vOrdenRutaPorFechaVendedor'),
		])),
	path('clientes/', include([
		path('page/<int:page>/', views.clientes, name='vListaClientes'),
		path('buscar/', views.clientes, name='vBuscarCliente'),
		path('<str:_id>/ver/', views.ver_cliente, name='vVerCliente'),
		path('nuevo/', views.nuevo_cliente, name='vNuevoCliente'),
		path('<str:_id>/editar/', views.editar_cliente, name='vEditarCliente'),
		])),
	path('vendedores/', include([
		path('page/<int:page>/', views.lista_vendedores, name='vListaVendedores'),
		path('<int:_id>/ver/', views.ver_vendedor, name='vVerVendedor'),
		path('buscar/', views.buscar_vendedor, name='vBuscarVendedor'),
		path('nuevo/', views.nuevo_vendedor, name='vNuevoVendedor'),
		path('<int:_id>/editar/', views.editar_vendedor, name='vEditarVendedor'),
		path('<int:_id>/desactivar/', views.desactivar_vendedor, name='vDesactivarVendedor'),
		])),
	path('rutas/', include([
		path('', views.lista_rutas, name='vListaRutas'),
		path('nueva/', views.nueva_ruta, name='vNuevaRuta'),
		path('<int:_id>/ver/', views.ver_ruta, name='vVerRuta'),
		path('<int:_id>/editar/', views.editar_ruta, name='vEditarRuta'),
		path('<int:_id>/eliminar/', views.eliminar_ruta, name='vEliminarRuta'),
		])),
]