from django.urls import path, include
from . import views

app_name = 'facturacion'

urlpatterns = [
	path('', views.index, name = 'vIndexFacturacion'),
	path('ventas/', include([
		path('periodo/', views.ventas_periodo, name='vVentasPeriodo'),
		path('rango/<str:inicio>/<str:final>/', views.ventas_rango, name='vVentasRango'),
		])),
	path('proformas/', include([
		path('', views.lista_proformas, name='vListaProformas'),
		path('<str:todas>/', views.lista_proformas, name='vListaTodasProformas'),
		path('rango/<str:inicio>/<str:final>/', views.lista_proformas_rango, name='vListaProformasRango'),
		path('nueva/', views.nueva_proforma, name='vNuevaProforma'),
		path('ver/<int:_id>/', views.ver_proforma, name='vVerProforma'),
		path('editar/<int:_id>/', views.editar_proforma, name='vEditarProforma'),
		path('reemitir/<int:_id>/', views.reemitir_proforma, name='vReemitirProforma'),
		path('detalle/editar/<int:_id>/', views.editar_detalle_proforma, name='vEditarDetalleProforma'),
		path('anular/', views.anular_proforma, name='vAnularProforma'),
		])),
	path('facturas/', include([
		path('nueva/', views.nueva_factura, name='vNuevaFactura'),
		path('ver/<int:_id>/', views.ver_factura, name='vVerFactura'),
		path('imprimir/<int:_id>/', views.imprimirFactura, name='vImprimirFactura'),
		#path('liquidar/<int:vendedor>/<str:fecha>', views.liquidarFactura, name='vLiquidarFactura'),
		path('editar/<int:_id>/', views.editar_factura, name='vEditarFactura'),
		path('detalle/editar/<int:_id>/', views.editar_detalle_factura, name='vEditarDetalleFactura'),
		path('cancelar/<int:_id>/', views.cancelarFactura, name='vCancelarFactura'),
		path('anular/<int:_id>/', views.anularFactura, name='vAnularFactura'),
		path('entregar/<int:_id>/', views.entregarFactura, name='vEntregarFactura'),
		path('detalle/<int:_id>/eliminar/', views.eliminarDetalleFactura, name='vEliminarDetalleFactura'),
		path('por-fecha/<str:fecha>/', views.facturasPorFecha, name='vFacturasPorFecha'),
		path('por-vendedor/<int:_id>/', views.facturasPorVendedor, name='vFacturasPorVendedor'),
		path('por-fecha-vendedor/<str:fecha>/<int:_id>/', views.facturasVendedorFecha, name='vFacturasVendedorFecha'),
		#path('pendientes/', views.listaFacturasPendientes, name='vListaFacturasPendientes'),
		])),
	path('orden-ruta/', include([
		path('', views.lista_ordenes_ruta, name='vListaOrdenesRuta'),
		path('nueva/', views.nueva_orden_ruta, name='vNuevaOrdenRuta'),
		path('ver/<int:_id>/', views.ver_orden_ruta, name='vVerOrdenRuta'),
		path('autorizar/<int:_id>/', views.autorizar_orden_ruta, name='vAutorizarOrdenRuta'),
		path('editar/<int:_id>/', views.editar_orden_ruta, name='vEditarOrdenRuta'),
		#path('eliminar/<int:_id>/', views.eliminar_orden_ruta, name='vEliminarOrdenRuta'),
		path('entregar/<int:_id>/', views.entregar_orden_ruta, name='vEntregarOrdenRuta'),
		path('anular/<int:_id>/', views.anular_orden_ruta, name='vAnularOrdenRuta'),
		path('liquidar/<int:_id>/', views.liquidar_orden_ruta, name='vLiquidarOrdenRuta'),
		path('detalle/<int:_id>/eliminar/', views.eliminar_detalle_orden_ruta, name='vEliminarDetalleOrdenRuta'),
		#path('detalle/<int:_id>/entregar/', views.entregar_detalle_orden_ruta, name='vEntregarDetalleOrdenRuta'),
		path('por-fecha/<str:fecha>/', views.ordenRutaPorFecha, name='vOrdenRutaPorFecha'),
		path('por-vendedor/<int:_id>/', views.ordenRutaPorVendedor, name='vOrdenRutaPorVendedor'),
		path('por-fecha-vendedor/<str:fecha>/<int:_id>/', views.ordenRutaPorFechaVendedor, name='vOrdenRutaPorFechaVendedor'),
		])),
	path('clientes/', include([
		path('', views.listaClientes, name='vListaClientes'),
		path('ver/<str:id>/', views.verCliente, name='vVerCliente'),
		path('nuevo/', views.nuevoCliente, name='vNuevoCliente'),
		path('editar/<str:id>/', views.editarCliente, name='vEditarCliente'),
		])),
	path('vendedores/', include([
		path('', views.listaVendedores, name='vListaVendedores'),
		path('ver/<int:id>/', views.verVendedor, name='vVerVendedor'),
		path('buscar/<str:cedula>/', views.buscarVendedor, name='vBuscarVendedor'),
		path('nuevo/', views.nuevoVendedor, name='vNuevoVendedor'),
		path('editar/<int:id>/', views.editarVendedor, name='vEditarVendedor'),
		path('desactivar/<int:id>/', views.desactivarVendedor, name='vDesactivarVendedor'),
		])),
	path('camiones/', include([
		path('', views.listaCamiones, name='vListaCamiones'),
		path('nuevo/', views.nuevoCamion, name='vNuevoCamion'),
		path('editar/<int:id>/', views.editarCamion, name='vEditarCamion'),
		path('eliminar/<int:id>/', views.eliminarCamion, name='vEliminarCamion'),
		])),
	path('rutas/', include([
		path('', views.listaRutas, name='vListaRutas'),
		path('nueva/', views.nuevaRuta, name='vNuevaRuta'),
		path('editar/<int:_id>/', views.editarRuta, name='vEditarRuta'),
		path('eliminar/<int:_id>/', views.eliminarRuta, name='vEliminarRuta'),
		])),
]